#!/sbin/sh

F_KERNEL_VER="Linux localhost 2.6.32.9-g55626e1 #1 PREEMPT Sun Nov 7 23:24:32 CST 2010 armv7l GNU/Linux"
G_KERNEL_VER="Linux localhost 2.6.32.9-g34b306d #2 PREEMPT Mon Jun 27 14:02:56 PDT 2011 armv7l GNU/Linux"

DET_KERNEL_VER="$(uname -a)"

if [ "${DET_KERNEL_VER}" == "${F_KERNEL_VER}" \
        -o "${DET_KERNEL_VER}" == "${G_KERNEL_VER}" ] ; then
    exit 0
else
    exit 1
fi
