#!/system/xbin/bash

# booting into recovery, so we need to touch /data/.recovery_mode

MNT_POINT="/data"
MNT_INFO=$(mount | awk -v mnt=$MNT_POINT '{if ($3 == mnt) print $0}')

if [ "$MNT_INFO" == "" ] ; then
	# need to mount /data to do this
	mount -o nosuid,nodev,noatime,nodiratime "/dev/block/mmcblk1p24" "/data"
	touch "/data/.recovery_mode"
	umount "/data"
else
	# /data already mounted, just touch the file
	touch "/data/.recovery_mode"
fi
