#!/system/xbin/bash

REASON=$1

if [ "$REASON" == "recovery" ] ; then
	# booting into recovery, so we need to touch /data/.recovery_mode

	MNT_POINT="/data"
	MNT_INFO=$(mount | awk -v mnt=$MNT_POINT '{if ($3 == mnt) print $0}')

	if [ "$MNT_INFO" == "" ] ; then
		# need to mount /data to do this
		mount -o nosuid,nodev,noatime,nodiratime "/dev/block/mmcblk1p24" "/data"
		touch "/data/.recovery_mode"
		umount "/data"
	else
		# /data already mounted, just touch the file
		touch "/data/.recovery_mode"
	fi
	# we don't echo anything here so the system will attempt a standard reboot
else
	# just echo the reason, we can't handle it anyway
	echo "$REASON"
fi
